{ lib, stdenv, buildGoModule, fetchFromGitHub }:

buildGoModule rec {
  pname = "sliver";
  version = "1.7.3";

  src = fetchFromGitHub {
    owner = "BishopFox";
    repo = "sliver";
    rev = "v${version}";
    hash = "sha256-3FYiDQiirc/VE9HEDny7/7x69XHQbylXPuKpcNJgLHw=";
  };

  vendorHash = null;

  ldflags = [
    "-s" "-w"
    "-X github.com/bishopfox/sliver/client/command/update.SliverPublicKey=RWTZPg959v3b7tLG7VzKHRB1/QT+d3c71Uzetfa44qAoX5rH7mGoQTTR"
    "-X github.com/bishopfox/sliver/client/assets.DefaultArmoryPublicKey=RWSBpxpRWDrD7Fe+VvRE3c2VEDC2NK80rlNCj+BX0gz44Xw07r6KQD9L"
    "-X github.com/bishopfox/sliver/client/assets.DefaultArmoryRepoURL=https://api.github.com/repos/sliverarmory/armory/releases"
  ];

  preBuild = let
    os = if stdenv.hostPlatform.isLinux then "linux"
      else if stdenv.hostPlatform.isDarwin then "darwin"
      else "windows";
    arch = if stdenv.hostPlatform.isAarch64 then "arm64" else "amd64";
  in ''
    mkdir -p server/assets/fs/${os}/${arch}

    # Minimal valid empty ZIP to satisfy go:embed fs/*.zip.
    # The real src.zip (Go source for implant cross-compilation, ~37MB)
    # is generated by util/cmd/assets and not committed; without any
    # .zip file in server/assets/fs/ the embed pattern fails to compile.
    printf '\x50\x4b\x05\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' \
      > server/assets/fs/src.zip

    # Placeholder so go:embed fs/${os}/${arch}/* has something to match.
    # The real toolchain blobs (go.zip, zig.tar.xz, garble) are skipped
    # here; the server downloads them at runtime via 'sliver-server unpack'.
    touch server/assets/fs/${os}/${arch}/PLACEHOLDER
  '';

  buildPhase = ''
    runHook preBuild

    CGO_ENABLED=0 go build -mod=vendor -trimpath \
      -tags "go_sqlite,server" \
      -ldflags '${lib.strings.concatStringsSep " " ldflags}' \
      -o sliver-server ./server

    CGO_ENABLED=0 go build -mod=vendor -trimpath \
      -tags "go_sqlite,client" \
      -ldflags '${lib.strings.concatStringsSep " " ldflags}' \
      -o sliver-client ./client

    runHook postBuild
  '';

  installPhase = ''
    install -Dm755 sliver-server $out/bin/sliver-server
    install -Dm755 sliver-client $out/bin/sliver-client
  '';

  checkPhase = "";

  meta = with lib; {
    description = "Adversary Emulation Framework";
    longDescription = ''
      Sliver is an open source cross-platform adversary emulation/red team
      framework, used by security professionals, penetration testers, and
      red-teamers. It is the alternative to commercial C2 frameworks such
      as Cobalt Strike and Brute Ratel.
    '';
    homepage = "https://github.com/BishopFox/sliver";
    changelog = "https://github.com/BishopFox/sliver/releases/tag/v${version}";
    license = licenses.gpl3Only;
    platforms = platforms.linux ++ platforms.darwin;
  };
}
